<?php

namespace Beneylu\BeneyluBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstallRepository extends EntityRepository
{
}
